# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations (initMessage)

from typing import Optional
from typing_extensions import Literal

from .._resource import AsyncAPIResource
from ..lib.websocket_streaming import SpeechSession

__all__ = ["AsyncSessionsResource", "SpeechSession"]


class AsyncSessionsResource(AsyncAPIResource):
    async def create(
        self,
        *,
        voice: str,
        format: Optional[Literal["mp3", "pcm_s16le", "pcm_f32le", "ulaw", "webm"]] = None,
        language: Optional[
            Literal[
                "auto",
                "ar",
                "de",
                "en",
                "es",
                "fr",
                "hi",
                "id",
                "it",
                "ja",
                "ko",
                "nl",
                "pl",
                "pt",
                "ru",
                "sv",
                "th",
                "tr",
                "uk",
                "ur",
                "vi",
                "zh",
            ]
        ] = None,
        return_extras: Optional[bool] = None,
        sample_rate: Optional[Literal[24000, 16000, 8000]] = None,
    ) -> SpeechSession:
        """
        Stream text to our servers and receive synthesized speech in real-time. Great for latency-sensitive applications and situations where you don't have all the text upfront.

        Args:
          voice: The voice ID to use for synthesis, obtained from 'List voices' API
          format: The desired output format of the audio.
            - `mp3`: 96kbps MP3 audio.
            - `pcm_s16le`: PCM signed 16-bit little-endian audio.
            - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
            - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
            - `webm`: WebM format with Opus audio codec.
          language: The desired language. Two letter ISO 639-1 code. Defaults to auto language detection.
          return_extras: Controls whether the server will return extra information about the synthesis
          sample_rate: The desired output audio sample rate
        """
        session = SpeechSession(
            self._client.api_key,
            voice=voice,
            format=format,
            language=language,
            return_extras=return_extras,
            sample_rate=sample_rate,
        )
        await session.connect()
        return session
