# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations (initMessage)

from __future__ import annotations

import json
from typing import Any, Dict, Final, Union, Literal, Optional

import websockets
from pydantic import BaseModel

from .._resource import AsyncAPIResource
from .._api_version import LMNT_API_VERSION
from ..types.speech_stream_error import SpeechStreamError as ErrorMessage
from ..types.speech_stream_extras import SpeechStreamExtras as ExtrasMessage

__all__ = ["AsyncSessionsResource", "SpeechSession"]

URL_STREAMING: Final = "wss://api.lmnt.com/v1/ai/speech/stream"


class AudioMessage(BaseModel):
  """Audio message containing synthesized speech data."""

  type: Literal["audio"] = "audio"
  audio: bytes


class CompleteMessage(BaseModel):
  """Complete message for commands (reset/flush).

  Not yet in asyncapi.yaml — V2-protocol ack message; carbonsteel will generate it once the
  spec V2 alignment lands. Until then, kept hand-written so the SpeechSession dispatch
  surface stays intact.
  """

  type: Literal["complete"] = "complete"
  complete: Literal["reset", "flush"]
  nonce: int


SpeechSessionResponse = Union[AudioMessage, ExtrasMessage, ErrorMessage, CompleteMessage]


class UnexpectedMessageError(Exception):
  """Exception raised when an unexpected message is received from the server."""

  def __init__(self, message: str):
    self.message = message
    super().__init__(f"Unexpected message received from server: {message}")


class SpeechSession:
  """Async websocket connection for LMNT speech session."""

  def __init__(
      self,
      api_key: str,
      voice: str,
      format: Optional[Literal["mp3", "pcm_s16le", "pcm_f32le", "ulaw", "webm"]] = None,
      language: Optional[
          Literal[
          "auto",
              "ar",
              "as",
              "bn",
              "cs",
              "da",
              "de",
              "en",
              "es",
              "fi",
              "fr",
              "hi",
              "id",
              "it",
              "ja",
              "ko",
              "ml",
              "mr",
              "nl",
              "pl",
              "pt",
              "ru",
              "sk",
              "sv",
              "ta",
              "te",
              "th",
              "tr",
              "uk",
              "ur",
              "vi",
              "zh",
          ]
      ] = None,
      return_extras: Optional[bool] = None,
      sample_rate: Optional[Literal[24000, 16000, 8000]] = None,
  ):
    self.api_key = api_key
    self.voice = voice
    self.format = format
    self.language = language
    self.return_extras = return_extras
    self.sample_rate = sample_rate
    self.websocket: Optional[Any] = None
    self.nonce: int = 0

  async def connect(self) -> None:
    """Establish the websocket connection."""
    self.websocket = await websockets.connect(URL_STREAMING)
    init_msg = {
        "X-API-Key": self.api_key,
        "lmnt-version": LMNT_API_VERSION,
        "voice": self.voice,
    }
    if self.format:
      init_msg["format"] = self.format
    if self.language:
      init_msg["language"] = self.language
    if self.return_extras:
      init_msg["return_extras"] = str(self.return_extras)
    if self.sample_rate:
      init_msg["sample_rate"] = str(self.sample_rate)
    if self.websocket is not None:
      await self.websocket.send(json.dumps(init_msg))

  async def append_text(self, text: str) -> None:
    """Append text to be synthesized."""
    await self._send_message({"text": text})

  async def flush(self) -> int:
    """Flush the current text buffer."""
    self.nonce += 1
    await self._send_message({"command": "flush", "nonce": self.nonce})
    return self.nonce

  async def reset(self) -> int:
    """Reset the current text buffer."""
    self.nonce += 1
    await self._send_message({"command": "reset", "nonce": self.nonce})
    return self.nonce

  async def finish(self) -> None:
    """Mark the session as finished."""
    await self._send_message({"command": "eof"})

  async def close(self) -> None:
    """Close the websocket connection."""
    if self.websocket is not None:
      await self.websocket.close()
      self.websocket = None

  async def _send_message(self, message: Dict[str, Any]) -> None:
    """Send a message through the websocket."""
    if self.websocket is not None:
      await self.websocket.send(json.dumps(message))

  def __aiter__(self) -> SpeechSession:
    """Return the async iterator."""
    return self

  async def __anext__(self) -> SpeechSessionResponse:
    """Get the next speech session response."""
    if not self.websocket:
      raise StopAsyncIteration
    try:
      message = await self.websocket.recv()

      if isinstance(message, str):
        return self._parse_text_message(message)
      elif isinstance(message, bytes):
        return AudioMessage(type="audio", audio=message)
      else:
        raise UnexpectedMessageError(f"Unexpected message type: {type(message)}")

    except websockets.exceptions.ConnectionClosed as err:
      raise StopAsyncIteration from err

  def _parse_text_message(self, text_data: str) -> SpeechSessionResponse:
    """Parse a text message from the server."""
    try:
      message_json = json.loads(text_data)
    except json.JSONDecodeError as err:
      raise ValueError(f"Invalid JSON received from server: {text_data}") from err

    if "error" in message_json:
      return ErrorMessage.model_construct(**message_json)

    if "complete" in message_json:
      return CompleteMessage.model_construct(**message_json)

    if self.return_extras and (
        message_json.get("timestamps") or message_json.get("warning") or message_json.get("buffer_empty") is not None
    ):
      return ExtrasMessage.model_construct(**message_json)

    raise UnexpectedMessageError(f"Unexpected message: {text_data}")


class AsyncSessionsResource(AsyncAPIResource):
  async def create(
      self,
      *,
      voice: str,
      format: Optional[Literal["mp3", "pcm_s16le", "pcm_f32le", "ulaw", "webm"]] = None,
      language: Optional[
          Literal[
          "auto",
              "ar",
              "as",
              "bn",
              "cs",
              "da",
              "de",
              "en",
              "es",
              "fi",
              "fr",
              "hi",
              "id",
              "it",
              "ja",
              "ko",
              "ml",
              "mr",
              "nl",
              "pl",
              "pt",
              "ru",
              "sk",
              "sv",
              "ta",
              "te",
              "th",
              "tr",
              "uk",
              "ur",
              "vi",
              "zh",
          ]
      ] = None,
      return_extras: Optional[bool] = None,
      sample_rate: Optional[Literal[24000, 16000, 8000]] = None,
  ) -> SpeechSession:
    """
    Stream text to our servers and receive generated speech in real-time. Great for latency-sensitive applications and situations where you don't have all the text upfront.

    Args:
      voice: The voice ID to use for speech generation, obtained from 'List voices' API
      format: The desired output format of the audio.
        - `mp3`: 96kbps MP3 audio.
        - `pcm_s16le`: PCM signed 16-bit little-endian audio.
        - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
        - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
        - `webm`: WebM format with Opus audio codec.
      language: The desired language. Two letter ISO 639-1 code. Defaults to auto language detection.
      return_extras: Controls whether the server will return extra information about the generated speech
      sample_rate: The desired output audio sample rate
    """
    session = SpeechSession(
        self._client.api_key,
        voice=voice,
        format=format,
        language=language,
        return_extras=return_extras,
        sample_rate=sample_rate,
    )
    await session.connect()
    return session
