# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations

from __future__ import annotations

import json
from typing import Any, List, Union, AsyncIterator

import pytest
import websockets

from lmnt import AsyncLmnt
from lmnt.resources.sessions import (
    AudioMessage,
    ErrorMessage,
    ExtrasMessage,
    SpeechSession,
    SpeechSessionResponse,
)

Frame = Union[str, bytes]


class _FakeWebSocket:
  """Minimal stand-in for the `websockets` connection interface used by `SpeechSession`."""

  def __init__(self, frames: List[Frame]) -> None:
    self._frames = list(frames)
    self.sent: List[str] = []

  async def send(self, message: str) -> None:
    self.sent.append(message)

  async def recv(self) -> Frame:
    if not self._frames:
      raise websockets.exceptions.ConnectionClosed(rcvd=None, sent=None)
    return self._frames.pop(0)

  async def close(self) -> None:
    return None


@pytest.fixture
def fake_connect(monkeypatch: pytest.MonkeyPatch):
  """Install a fake `websockets.connect` that hands back a `_FakeWebSocket` preloaded
  with the given frames."""

  def installer(frames: List[Frame]) -> _FakeWebSocket:
    fake = _FakeWebSocket(frames)

    async def _connect(_url: str) -> _FakeWebSocket:
      return fake

    monkeypatch.setattr("lmnt.resources.sessions.websockets.connect", _connect)
    return fake

  return installer


async def _drain(session: SpeechSession) -> List[SpeechSessionResponse]:
  received: List[SpeechSessionResponse] = []
  aiter: AsyncIterator[SpeechSessionResponse] = session.__aiter__()
  while True:
    try:
      received.append(await aiter.__anext__())
    except StopAsyncIteration:
      break
  return received


class TestAsyncSessions:
  @pytest.mark.asyncio
  async def test_init_message_operation(self, fake_connect: Any) -> None:
    """The SDK ships an init message on connect with X-API-Key, lmnt-version,
    and every required `initMessage` property from the spec."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    await client.speech.sessions.create(voice="voice-id")

    assert len(fake.sent) == 1
    sent = json.loads(fake.sent[0])
    assert sent["X-API-Key"] == "test-api-key"
    assert sent["lmnt-version"] == "1.1"
    assert sent["voice"] == "voice-id"

  @pytest.mark.asyncio
  async def test_text_streaming_operation(self, fake_connect: Any) -> None:
    """`append_text` sends a `textMessage` frame whose key is the schema's required
    property name."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    await session.append_text("hello world")

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"text": "hello world"}

  @pytest.mark.asyncio
  async def test_flush_operation(self, fake_connect: Any) -> None:
    """`flush()` sends a `flushCommand` frame. Returns the nonce."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    nonce = await session.flush()
    assert nonce == 1

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"command": "flush", "nonce": 1}

  @pytest.mark.asyncio
  async def test_eof_operation(self, fake_connect: Any) -> None:
    """`finish()` sends a `eofCommand` frame."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    await session.finish()

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"command": "eof"}

  @pytest.mark.asyncio
  async def test_receive_audio(self, fake_connect: Any) -> None:
    """A binary `audio` frame yields an `AudioMessage` from the iterator."""
    audio_bytes = b"\x00\x01\x02\x03"
    fake_connect([audio_bytes])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, AudioMessage)
    assert only.type == "audio"
    assert only.audio == audio_bytes

  @pytest.mark.asyncio
  async def test_receive_extras(self, fake_connect: Any) -> None:
    """A `extras` JSON frame matching the spec's schema yields an
    `ExtrasMessage` from the iterator."""
    extras_payload = {
        "timestamps": [{"text": "hi", "start": 0.0, "duration": 0.5}],
        "buffer_empty": True,
        "warning": None,
    }
    fake_connect([json.dumps(extras_payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id", return_extras=True)
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, ExtrasMessage)
    assert only.type == "extras"
    assert only.timestamps is not None
    assert len(only.timestamps) == 1
    assert only.buffer_empty is True

  @pytest.mark.asyncio
  async def test_receive_error(self, fake_connect: Any) -> None:
    """An `error` JSON frame yields an `ErrorMessage` from the iterator."""
    error_payload = {"error": "voice not found"}
    fake_connect([json.dumps(error_payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, ErrorMessage)
    assert only.type == "error"
    assert only.error == "voice not found"
