# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations

from __future__ import annotations

import json
from typing import Any, List, Union, AsyncIterator

import pytest
import websockets

from lmnt import AsyncLmnt
from lmnt.resources.sessions import (
  SpeechSession,
  SpeechSessionAudio,
  SpeechSessionError,
  SpeechSessionReady,
  SpeechSessionResponse,
  SpeechSessionTimestamps,
  SpeechSessionFlushComplete,
  SpeechSessionResetComplete,
)

Frame = Union[str, bytes]


class _FakeWebSocket:
  """Minimal stand-in for the `websockets` connection interface used by `SpeechSession`."""

  def __init__(self, frames: List[Frame]) -> None:
    self._frames = list(frames)
    self.sent: List[str] = []

  async def send(self, message: str) -> None:
    self.sent.append(message)

  async def recv(self) -> Frame:
    if not self._frames:
      raise websockets.exceptions.ConnectionClosed(rcvd=None, sent=None)
    return self._frames.pop(0)

  async def close(self) -> None:
    return None


@pytest.fixture
def fake_connect(monkeypatch: pytest.MonkeyPatch):
  """Install a fake `websockets.connect` that hands back a `_FakeWebSocket` preloaded
  with the given frames."""

  def installer(frames: List[Frame]) -> _FakeWebSocket:
    fake = _FakeWebSocket(frames)

    async def _connect(_url: str) -> _FakeWebSocket:
      return fake

    monkeypatch.setattr("lmnt.resources.sessions.websockets.connect", _connect)
    return fake

  return installer


async def _drain(session: SpeechSession) -> List[SpeechSessionResponse]:
  received: List[SpeechSessionResponse] = []
  aiter: AsyncIterator[SpeechSessionResponse] = session.__aiter__()
  while True:
    try:
      received.append(await aiter.__anext__())
    except StopAsyncIteration:
      break
  return received


class TestAsyncSessions:
  @pytest.mark.asyncio
  async def test_init_operation(self, fake_connect: Any) -> None:
    """On connect, the SDK sends the `init` message with every required property from the spec."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    await client.speech.sessions.create(voice="voice-id")

    assert len(fake.sent) == 1
    sent = json.loads(fake.sent[0])
    assert sent["X-API-Key"] == "test-api-key"
    assert sent["lmnt-version"] == "1.1"
    assert sent["voice"] == "voice-id"

  @pytest.mark.asyncio
  async def test_text_operation(self, fake_connect: Any) -> None:
    """`send_text(text)` sends a `text` frame."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    await session.send_text("text-value")

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"type": "text", "text": "text-value"}

  @pytest.mark.asyncio
  async def test_flush_operation(self, fake_connect: Any) -> None:
    """`send_flush()` sends a `flush` frame. Returns the nonce."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    nonce = await session.send_flush()
    assert nonce == 1

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"type": "flush", "nonce": 1}

  @pytest.mark.asyncio
  async def test_reset_operation(self, fake_connect: Any) -> None:
    """`send_reset()` sends a `reset` frame. Returns the nonce."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    nonce = await session.send_reset()
    assert nonce == 1

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"type": "reset", "nonce": 1}

  @pytest.mark.asyncio
  async def test_finish_operation(self, fake_connect: Any) -> None:
    """`send_finish()` sends a `finish` frame."""
    fake = fake_connect([])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    await session.send_finish()

    assert len(fake.sent) == 2
    assert json.loads(fake.sent[1]) == {"type": "finish"}

  @pytest.mark.asyncio
  async def test_receive_ready(self, fake_connect: Any) -> None:
    """A `ready` JSON frame yields a `SpeechSessionReady` from the iterator."""
    payload = {"type": "ready", "request_id": "request_id-value"}
    fake_connect([json.dumps(payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, SpeechSessionReady)
    assert only.type == "ready"
    assert only.request_id == "request_id-value"

  @pytest.mark.asyncio
  async def test_receive_audio(self, fake_connect: Any) -> None:
    """A binary `audio` frame yields a `SpeechSessionAudio` from the iterator."""
    payload = b"\x00\x01\x02\x03"
    fake_connect([payload])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, SpeechSessionAudio)
    assert only.type == "audio"
    assert only.audio == payload

  @pytest.mark.asyncio
  async def test_receive_timestamps(self, fake_connect: Any) -> None:
    """A `timestamps` JSON frame yields a `SpeechSessionTimestamps` from the iterator."""
    payload = {"type": "timestamps", "timestamps": [{"text": "hi", "start": 0.0, "duration": 0.5}]}
    fake_connect([json.dumps(payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id", return_timestamps=True)
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, SpeechSessionTimestamps)
    assert only.type == "timestamps"
    assert only.timestamps is not None
    assert len(only.timestamps) == 1

  @pytest.mark.asyncio
  async def test_receive_flush_complete(self, fake_connect: Any) -> None:
    """A `flush_complete` JSON frame yields a `SpeechSessionFlushComplete` from the iterator."""
    payload = {"type": "flush_complete", "nonce": 1}
    fake_connect([json.dumps(payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, SpeechSessionFlushComplete)
    assert only.type == "flush_complete"
    assert only.nonce == 1

  @pytest.mark.asyncio
  async def test_receive_reset_complete(self, fake_connect: Any) -> None:
    """A `reset_complete` JSON frame yields a `SpeechSessionResetComplete` from the iterator."""
    payload = {"type": "reset_complete", "nonce": 1}
    fake_connect([json.dumps(payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, SpeechSessionResetComplete)
    assert only.type == "reset_complete"
    assert only.nonce == 1

  @pytest.mark.asyncio
  async def test_receive_error(self, fake_connect: Any) -> None:
    """A `error` JSON frame yields a `SpeechSessionError` from the iterator."""
    payload = {"type": "error", "error": None, "request_id": "request_id-value"}
    fake_connect([json.dumps(payload)])

    client = AsyncLmnt(api_key="test-api-key")
    session = await client.speech.sessions.create(voice="voice-id")
    received = await _drain(session)

    assert len(received) == 1
    only = received[0]
    assert isinstance(only, SpeechSessionError)
    assert only.type == "error"
    assert only.request_id == "request_id-value"
