# Hand-written test for the WebSocket sessions resource. Not generated by carbonsteel.
#
# `tests/api_resources/test_*.py` for REST resources are generated against respx (httpx
# mocking). The sessions resource opens a WebSocket via `websockets.connect`, which respx
# can't mock — so this file monkeypatches the connect entry point directly.

from __future__ import annotations

import json
from typing import Any, List, Union, AsyncIterator

import pytest
import websockets

from lmnt import AsyncLmnt
from lmnt.lib.websocket_streaming import (
    AudioMessage,
    ErrorMessage,
    ExtrasMessage,
    SpeechSession,
    SpeechSessionResponse,
)

Frame = Union[str, bytes]


class _FakeWebSocket:
    """Minimal stand-in for the `websockets` connection interface used by `SpeechSession`."""

    def __init__(self, frames: List[Frame]) -> None:
        self._frames = list(frames)
        self.sent: List[str] = []

    async def send(self, message: str) -> None:
        self.sent.append(message)

    async def recv(self) -> Frame:
        if not self._frames:
            # Mirrors `websockets`' behavior on a server-closed connection: the next recv
            # raises ConnectionClosed, which SpeechSession.__anext__ converts to StopAsyncIteration.
            raise websockets.exceptions.ConnectionClosed(rcvd=None, sent=None)
        return self._frames.pop(0)

    async def close(self) -> None:
        return None


@pytest.fixture
def fake_connect(monkeypatch: pytest.MonkeyPatch):
    """Install a fake `websockets.connect` that hands back a `_FakeWebSocket` preloaded with
    the given frames. Returns an `installer` callable so each test picks its own frame list."""

    def installer(frames: List[Frame]) -> _FakeWebSocket:
        fake = _FakeWebSocket(frames)

        async def _connect(_url: str) -> _FakeWebSocket:
            return fake

        monkeypatch.setattr("lmnt.lib.websocket_streaming.websockets.connect", _connect)
        return fake

    return installer


async def _drain(session: SpeechSession) -> List[SpeechSessionResponse]:
    received: List[SpeechSessionResponse] = []
    aiter: AsyncIterator[SpeechSessionResponse] = session.__aiter__()
    while True:
        try:
            received.append(await aiter.__anext__())
        except StopAsyncIteration:
            break
    return received


class TestAsyncSessions:
    @pytest.mark.asyncio
    async def test_happy_path_extras_then_audio(self, fake_connect: Any) -> None:
        extras_payload = {
            "durations": [{"text": "hi", "start": 0.0, "duration": 0.5}],
            "warning": None,
            "buffer_empty": True,
        }
        audio_bytes = b"\x00\x01\x02\x03"
        fake = fake_connect([json.dumps(extras_payload), audio_bytes])

        client = AsyncLmnt(api_key="test-api-key")
        session = await client.speech.sessions.create(voice="voice-id", return_extras=True)

        # The init message was sent on connect with our voice + api_key.
        assert len(fake.sent) == 1
        sent_init = json.loads(fake.sent[0])
        assert sent_init["X-API-Key"] == "test-api-key"
        assert sent_init["voice"] == "voice-id"

        received = await _drain(session)
        assert len(received) == 2

        first = received[0]
        assert isinstance(first, ExtrasMessage)
        assert first.type == "extras"
        assert first.buffer_empty is True
        assert first.durations is not None
        assert len(first.durations) == 1
        assert first.durations[0].text == "hi"

        second = received[1]
        assert isinstance(second, AudioMessage)
        assert second.type == "audio"
        assert second.audio == audio_bytes

    @pytest.mark.asyncio
    async def test_error_path_error_then_close(self, fake_connect: Any) -> None:
        error_payload = {"error": "voice not found"}
        fake_connect([json.dumps(error_payload)])

        client = AsyncLmnt(api_key="test-api-key")
        session = await client.speech.sessions.create(voice="bad-voice")

        received = await _drain(session)
        assert len(received) == 1

        only = received[0]
        assert isinstance(only, ErrorMessage)
        assert only.type == "error"
        assert only.error == "voice not found"
