# Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths/v1/account/get/responses

from .._models import BaseModel

__all__ = ["AccountRetrieveResponse", "Plan", "Usage"]


class Plan(BaseModel):
  character_limit: int
  """The maximum number of characters per billing period allowed by your plan."""

  commercial_use_allowed: bool

  type: str
  """The type of plan you are subscribed to."""


class Usage(BaseModel):
  characters: int
  """The number of characters remaining in this billing period."""


class AccountRetrieveResponse(BaseModel):
  plan: Plan

  usage: Usage
