# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/duration

from .._models import BaseModel

__all__ = ["Duration"]


class Duration(BaseModel):
    duration: float
    """The overall duration of the text, in seconds"""

    start: float
    """The time at which the text starts, in seconds"""

    text: str
    """The text segment"""
