# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/session/errorBody

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["ErrorBody"]


class ErrorBody(BaseModel):
  message: str
  """Human-readable error message."""

  type: Literal[
    "invalid_request_error",
    "authentication_error",
    "permission_error",
    "not_found_error",
    "payment_required_error",
    "rate_limit_error",
    "internal_server_error",
  ]
  """Slug identifying the error category."""
