# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/timestamps/payload

from typing import List, Optional
from typing_extensions import Literal

from .._models import BaseModel
from .timestamp import Timestamp

__all__ = ["SpeechSessionTimestamps"]


class SpeechSessionTimestamps(BaseModel):
  type: Literal["timestamps"] = "timestamps"
  """Discriminator identifying this message type."""

  timestamps: Optional[List[Timestamp]] = None
  """Array of timestamp objects, one per generated text token.

    <Warning> The timestamps array resets its start time for each chunk of audio.

    </Warning>
    """
