# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/error

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechStreamError"]


class SpeechStreamError(BaseModel):
    error: str
    """Error message describing what went wrong.

    Connection will close immediately after error message.
    """

    type: Literal["error"] = "error"
