# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/error/payload

from typing_extensions import Literal

from .._models import BaseModel
from .error_body import ErrorBody

__all__ = ["SpeechSessionError"]


class SpeechSessionError(BaseModel):
  error: ErrorBody

  request_id: str
  """Per-session request ID for log correlation."""

  type: Literal["error"] = "error"
  """Discriminator identifying this message type."""
