# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/extras

from typing import List, Optional
from typing_extensions import Literal

from .duration import Duration
from .._models import BaseModel

__all__ = ["SpeechStreamExtras"]


class SpeechStreamExtras(BaseModel):
    type: Literal["extras"] = "extras"

    buffer_empty: Optional[bool] = None
    """Indicates whether the server has finished synthesizing all received text.

    Particularly useful when you have triggered a `flush`.
    """

    durations: Optional[List[Duration]] = None
    """Array of objects detailing the duration of each text token

    <Warning> The durations array resets its start time for each chunk of audio.

    </Warning>
    """

    warning: Optional[str] = None
    """Contains any warnings encountered during synthesis"""
