# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/initMessage

from typing import Optional
from typing_extensions import Literal

from pydantic import Field

from .._models import BaseModel

__all__ = ["SpeechStreamInitMessage"]


class SpeechStreamInitMessage(BaseModel):
    x_api_key: str = Field(alias="X-API-Key")
    """Your API key obtained from your account page"""

    type: Literal["initMessage"] = "initMessage"

    voice: str
    """The voice ID to use for synthesis, obtained from 'List voices' API"""

    format: Optional[Literal["mp3", "pcm_s16le", "pcm_f32le", "ulaw", "webm"]] = None
    """The desired output format of the audio.

    - `mp3`: 96kbps MP3 audio.
    - `pcm_s16le`: PCM signed 16-bit little-endian audio.
    - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
    - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
    - `webm`: WebM format with Opus audio codec.
    """

    language: Optional[
        Literal[
            "auto",
            "ar",
            "de",
            "en",
            "es",
            "fr",
            "hi",
            "id",
            "it",
            "ja",
            "ko",
            "nl",
            "pl",
            "pt",
            "ru",
            "sv",
            "th",
            "tr",
            "uk",
            "ur",
            "vi",
            "zh",
        ]
    ] = None
    """The desired language.

    Two letter ISO 639-1 code. Defaults to auto language detection.
    """

    return_extras: Optional[bool] = None
    """Controls whether the server will return extra information about the synthesis"""

    sample_rate: Optional[Literal[24000, 16000, 8000]] = None
    """The desired output audio sample rate"""
