# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/init/payload

from typing import Optional
from typing_extensions import Literal

from pydantic import Field

from .._models import BaseModel

__all__ = ["SpeechSessionInit"]


class SpeechSessionInit(BaseModel):
  x_api_key: str = Field(alias="X-API-Key")
  """Your API key obtained from your account page"""

  type: Literal["init"] = "init"
  """Discriminator identifying this message type."""

  voice: str
  """The voice ID to use for speech generation, obtained from 'List voices' API"""

  format: Optional[Literal["mp3", "pcm_s16le", "pcm_f32le", "ulaw", "webm"]] = None
  """The desired output format of the audio.

    - `mp3`: 96kbps MP3 audio.
    - `pcm_s16le`: PCM signed 16-bit little-endian audio.
    - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
    - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
    - `webm`: WebM format with Opus audio codec.
    """

  language: Optional[
    Literal[
      "auto",
      "ar",
      "as",
      "bn",
      "cs",
      "da",
      "de",
      "en",
      "es",
      "fi",
      "fr",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "ml",
      "mr",
      "nl",
      "pl",
      "pt",
      "ru",
      "sk",
      "sv",
      "ta",
      "te",
      "th",
      "tr",
      "uk",
      "ur",
      "vi",
      "zh",
    ]
  ] = None

  lmnt_version: Optional[str] = Field(default=None, alias="lmnt-version")
  """The LMNT API version that this client was built against."""

  return_timestamps: Optional[bool] = None
  """Controls whether the server will return timestamps for the generated speech"""

  sample_rate: Optional[Literal[24000, 16000, 8000]] = None
  """The desired output audio sample rate"""
