# Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths/v1/ai/speech/post/responses

from typing import List, Optional

from .._models import BaseModel

__all__ = ["SpeechGenerateDetailedResponse", "Timestamp"]


class Timestamp(BaseModel):
  duration: float
  """The spoken duration of the generated input element, in seconds."""

  start: float
  """The start time of the generated input element, in seconds."""

  text: str
  """The generated input element; beginning and ending with a short silence."""


class SpeechGenerateDetailedResponse(BaseModel):
  audio: str
  """
    The base64-encoded audio file; the format is determined by the `format`
    parameter.
    """

  timestamps: Optional[List[Timestamp]] = None
  """
    An array describing where each generated input element (words and non-words like
    spaces, punctuation, etc.) falls in the audio.
    """
