# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/ready/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionReady"]


class SpeechSessionReady(BaseModel):
  request_id: str  # pyright: ignore[reportIncompatibleVariableOverride, reportGeneralTypeIssues]
  """Per-session request ID.

    If you're reporting an issue, include this if possible to make debugging easier.
    """

  type: Literal["ready"] = "ready"
  """Discriminator identifying this message type."""
