# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/extras

from typing import List, Optional
from typing_extensions import Literal

from .._models import BaseModel
from .timestamp import Timestamp

__all__ = ["SpeechStreamExtras"]


class SpeechStreamExtras(BaseModel):
  type: Literal["extras"] = "extras"

  buffer_empty: Optional[bool] = None
  """
    Indicates whether the server has finished generating speech for all received
    text. Particularly useful when you have triggered a `flush`.
    """

  timestamps: Optional[List[Timestamp]] = None
  """Array of timestamp objects, one per generated text token.

    <Warning> The timestamps array resets its start time for each chunk of audio.

    </Warning>
    """

  warning: Optional[str] = None
  """Contains any warnings encountered during speech generation"""
