# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/flush/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionFlush"]


class SpeechSessionFlush(BaseModel):
  nonce: int
  """Client-chosen nonce; the server returns it in the matching `flush_complete`."""

  type: Literal["flush"] = "flush"
  """Discriminator identifying this message type."""
