# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/flush_complete/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionFlushComplete"]


class SpeechSessionFlushComplete(BaseModel):
  nonce: int
  """The nonce that was carried by the original `flush`."""

  type: Literal["flush_complete"] = "flush_complete"
  """Discriminator identifying this message type."""
