# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/eofCommand

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechStreamEofCommand"]


class SpeechStreamEofCommand(BaseModel):
    eof: Literal[True]
    """Signal the server that no more text will be sent"""

    type: Literal["eofCommand"] = "eofCommand"
