# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/flushCommand

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechStreamFlushCommand"]


class SpeechStreamFlushCommand(BaseModel):
    flush: Literal[True]
    """Force the server to synthesize the text it has without closing the connection"""

    type: Literal["flushCommand"] = "flushCommand"
