# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/audio/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionAudio"]


class SpeechSessionAudio(BaseModel):
  audio: bytes
  """Binary audio data returned from the server"""

  type: Literal["audio"] = "audio"
