# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/ready/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionReady"]


class SpeechSessionReady(BaseModel):
  request_id: str
  """
    Per-session request ID — same value as the `request-id` HTTP header on the WS
    upgrade response. Use it to correlate session activity with server-side logs.
    """

  type: Literal["ready"] = "ready"
  """Discriminator identifying this message type."""
