# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/reset/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionReset"]


class SpeechSessionReset(BaseModel):
  nonce: int
  """Client-chosen nonce; the server returns it in the matching `reset_complete`."""

  type: Literal["reset"] = "reset"
  """Discriminator identifying this message type."""
