# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/text/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionText"]


class SpeechSessionText(BaseModel):
  text: str
  """The text to generate speech from"""

  type: Literal["text"] = "text"
  """Discriminator identifying this message type."""
