# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/reset_complete/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionResetComplete"]


class SpeechSessionResetComplete(BaseModel):
  nonce: int
  """The nonce that was carried by the original `reset`."""

  type: Literal["reset_complete"] = "reset_complete"
  """Discriminator identifying this message type."""
