# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/messages/finish/payload

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechSessionFinish"]


class SpeechSessionFinish(BaseModel):
  type: Literal["finish"] = "finish"
  """Discriminator identifying this message type.

    Signal the server that no more text will be sent.
    """
