# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/textMessage

from typing_extensions import Literal

from .._models import BaseModel

__all__ = ["SpeechStreamTextMessage"]


class SpeechStreamTextMessage(BaseModel):
    text: str
    """The text to be synthesized into speech"""

    type: Literal["textMessage"] = "textMessage"
