# Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/components/schemas/timestamp

from .._models import BaseModel

__all__ = ["Timestamp"]


class Timestamp(BaseModel):
  duration: float
  """The spoken duration of the text segment, in seconds"""

  start: float
  """The time at which the text starts, in seconds"""

  text: str
  """The text segment"""
