# Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths/v1/ai/voice/{id}/put/responses

from .voice import Voice
from .._models import BaseModel

__all__ = ["VoiceUpdateResponse"]


class VoiceUpdateResponse(BaseModel):
    voice: Voice
    """Voice details"""
