# Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths/v1/ai/voice/post

from __future__ import annotations

from typing import List
from typing_extensions import Required, TypedDict

from .._types import FileTypes

__all__ = ["VoiceCreateParams"]


class VoiceCreateParams(TypedDict, total=False):
  file: Required[FileTypes]
  """
    The input audio file to train the voice with, as a binary `wav`, `mp3`, `mp4`,
    `m4a`, or `webm` attachment.

    - Max file size: 250 MB.
    """

  name: Required[str]
  """The display name for this voice"""

  description: str
  """A text description of this voice."""

  gender: str
  """A tag describing the gender of this voice. Has no effect on voice creation."""

  tags: List[str]
  """A list of tags to attach to this voice."""
