# Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths/v1/ai/voice/{id}/delete/responses

from .._models import BaseModel

__all__ = ["VoiceDeleteResponse"]


class VoiceDeleteResponse(BaseModel):
    success: bool
