# Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths/v1/ai/voice/list/get/responses

from typing import List
from typing_extensions import TypeAlias

from .voice import Voice

__all__ = ["VoiceListResponse"]

VoiceListResponse: TypeAlias = List[Voice]
